config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  resources :notes
  get '/note/new', to: 'notes#new'
  get '/note/:id/download', to: 'notes#download',  as: 'download_note_path'
  root to: "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :notes, dependent: :destroy
    belongs_to :user
    validates :name, presence: true, length: { maximum: 150, too_long: "%{count} characters is the maximum allowed" }
    validates_uniqueness_of :name, scope: :user_id

end

app/models/note.rb
class Note < ApplicationRecord

    belongs_to :book
    has_rich_text :content
    validates :title, presence: true, length: { maximum: 150, too_long: "%{count} characters is the maximum allowed" }
    validates_uniqueness_of :title, scope: :book_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :create_global_book

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :notes, through: :books

  def create_global_book
    books.create(:name => 'Global')
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = current_user.books
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
   @book = (current_user.books).create(book_params) 
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.name == 'Global'
        format.html { redirect_to @book, alert: "You can't  update the title of the global book!" }
      else
        if @book.update(book_params)
          format.html { redirect_to @book, notice: 'Book was successfully updated.' }
          format.json { render :show, status: :ok, location: @book }
        else
          format.html { render :edit }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    
    respond_to do |format|
      if @book.name == 'Global'
        format.html { redirect_to books_url, alert: "You can't  delete the global book!" }
        format.json { render json: 'You don`t delete the global book!' }
      else
        @book.destroy
      end
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = current_user.books.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name)
    end


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy, :download]

  # GET /notes
  # GET /notes.json
  def index
    @notes = current_user.notes
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new?id_book=<:id_book>
  def new
    @note = Note.new
    @note.book = (current_user.books).find(params[:id_book])
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /<id_book>/notes
  # POST /<id_book>/notes.json
  def create
    @note = ((current_user.books.find(params[:note][:id_book])).notes).create(note_params)
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /<id_book>/notes/1
  # PATCH/PUT /<id_book>/notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    p @note.content
    send_data (Grover.new(@note.content.body.to_s).to_pdf), :filename => "#{@note.title}.pdf"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field ">
    <div class="mb-3 ">
      <%= form.label :name, :class => "form-label" %>
      <%= form.text_field :name , :class => "form-control"%>
    <div>
  </div>
  <div class="actions mt-2">
    <%= form.submit :class => " btn btn-dark " %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

app/views/books/index.html.erb
<div class="row justify-content-md-center">
  <div class="col-5 col-xl-2">
    <h1 class="title">BOOKS</h1>
  </div>
  <div class="col">
    <%= link_to '+ NEW BOOK', new_book_path, :class => "btn btn-outline-dark "%>
  </div>
</div>
<div class="row ">
<% @books.each do |book| %>
  <div class="col-12">
    <div class="box container p-3   mb-3" style="min-width: 24em;">
      <div class="row align-items-center ml-3" >
        <div class="col-xl-10 col-8 align-self-center ">
          <div class="row ">
            <h1 class="title  "> <%= book.name %></h1>
          </div>
          <div class="row ">
            <h5 > CANTIDAD DE NOTAS: <%= book.notes.count %></h5>
          </div>
        </div>
        <div class="col align-self-center ">
          <div class="btn-group-vertical">
              <%= link_to '+ Add note', new_note_path(:id_book => book.id),  :class => "btn btn-outline-dark " %>

              <%= link_to '<i class="far fa-sticky-note"></i> Notes'.html_safe , book ,:class => "btn btn-outline-dark "%>

              <%= link_to '<i class="far fa-edit"></i> Edit'.html_safe , edit_book_path(book),:class => "btn btn-outline-dark " %>


              <%= link_to  '<i class="far fa-trash-alt"></i> Destroy'.html_safe, book, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-dark " %>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-5 col-xl-5">
    <p>
      <strong>Name:</strong>
        </p>
      <h1 class="title"><%= @book.name %></h1>

  </div>
</div>
  <div class="row justify-content-center">
<%= link_to '+ NEW NOTE', new_note_path(:id_book => @book.id), :class => "btn btn-outline-dark "%>
</div>
<div class="container text-center">
  <div class="row justify-content-start">
    <% @book.notes.each do |note| %>
      <div class="col-12 col-md-3 align-self-center m-4">
        <div class="box text-center" style="max-width: 20em; min-width: 18em;">
          <div class="row justify-content-center">
            <div class="col align-self-center">
              <div class="card-body">
                <h5 class="card-title title"><%= note.title %></h5>
                <p class="updated-text"><small class=" ">Updated <%= truncate(note.updated_at.to_s, length: 20,:omission => '') %></small></p>  
                <div class="btn-group-vertical ">
                    <%= link_to '<i class="fas fa-eye"></i></i> Show'.html_safe , note ,:class => "btn btn-outline-dark "%>
                    <%= link_to '<i class="far fa-edit"></i> Edit'.html_safe , edit_note_path(note),:class => "btn btn-outline-dark " %>
                    <%= link_to '<i class="fas fa-download"></i> Download'.html_safe , download_note_path_path(note) ,:class => "btn btn-outline-dark " %>
                    <%= link_to  '<i class="far fa-trash-alt"></i> Destroy'.html_safe, note, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-dark " %>
                </div>
              </div>
            </div> 
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Notes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :css %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <%# IMPORT FONTS %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500;900&display=swap" rel="stylesheet">
  </head>

  <body>
  <div class="wrapper">
   <% if user_signed_in? %>
    <%= render 'partials/nav' %>
    <%end%>
     <div id="content" class="mt-4 container-sm">
     
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <% if user_signed_in? %>
          <nav class="navbar mb-3 pl-0">

                <button type="button" id="sidebarCollapse" class="btn btn-dark">
                    <span>MENU</span>
                </button>

          </nav>
        <% end %>
        <%= yield %>
      </div>
  </div>
  </body>
<script>


            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });


</script>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>
      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <div class="mb-3">
      <%= form.label :title, :class => "form-label"%>
      <%= form.text_field :title, :class => "form-control"%>
    </div>
    <%= form.hidden_field :id_book, value: note.book.id %>
    <div class="container box p-4">
      <div class="mb-3">
        <%= form.label :content, :class => "form-label" %>
        <%= form.rich_text_area :content %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= form.submit :class => " btn btn-dark btn-block" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1 class="title">Editing Note</h1>

<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<h1 class="title" >Notes</h1>
<h5 class="text-center">These are all you notes:</h5>
<div class="container">
  <div class="row justify-content-start">
    <% @notes.each do |note| %>
      <div class="col-12 col-md-3 align-self-center m-4">
        <div class="box text-center" style="max-width: 20em; min-width: 18em;">
          <div class="row justify-content-center">
            <div class="col align-self-center">
              <div class="card-body">
                <h5 class="card-title title"><%= note.title %></h5>
                <p class="updated-text" style="color: black;"><small class=" ">Book: <%= truncate(note.book.name, length: 20,:omission => '') %></small></p>  
                <p class="updated-text"><small class=" ">Updated <%= truncate(note.updated_at.to_s, length: 20,:omission => '') %></small></p>  
                <div class="btn-group-vertical ">
                    <%= link_to '<i class="fas fa-eye"></i></i> Show'.html_safe , note ,:class => "btn btn-outline-dark "%>
                    <%= link_to '<i class="far fa-edit"></i> Edit'.html_safe , edit_note_path(note),:class => "btn btn-outline-dark " %>
                    <%= link_to '<i class="fas fa-download"></i> Download'.html_safe , download_note_path_path(note) ,:class => "btn btn-outline-dark " %>
                    <%= link_to  '<i class="far fa-trash-alt"></i> Destroy'.html_safe, note, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-dark " %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/notes/new.html.erb
<h1 class="title">New Note</h1>

<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<h5 class=" title"> From: <%= @note.book.name %></h5>
<div class="card">
  <h5 class="card-header"><%= @note.title %></h5>
  <div class="card-body">
    <%= @note.content %>
  </div>  
</div>
<div class="mt-2 mb-4">
<%= link_to 'Edit', edit_note_path(@note), :class => "btn btn-dark btn-block" %>
</div>

app/views/partials/_nav.html.erb
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3>MY NOTES</h3>
        </div>

        <ul class="list-unstyled components">
            <p>Welcome <%= current_user.email %></p>

            <li>
                <%= link_to 'Books', books_path %>
            </li>
            <li>
                <%= link_to 'Notes', notes_path %>
            </li>
            <li>
                <%= link_to 'Profile', edit_user_registration_path %>
            </li>
            <li>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            </li>

            
        </ul>
    </nav>